### ISSUE TITLE
Breaking change in Tibber API websockets

### ISSUE THREAD

**Issue by toini** [bisand/tibber-api#22]
Hi!

I would like to thank you for contributing to the community of Tibber users! We've added you to the list of people we respect! https://developer.tibber.com/respect

In order to improve the API resilience we are making a breaking change for websocket communication. Please see details at [developer site](https://developer.tibber.com/). Would you be able to adjust the implementation accordingly?

Also, note that recommended format for setting user agent header would be to include both the platform version and driver version for example like this: MyHomeAutomationDevice/1.2.3 bisand/4.1.0'

We're trying to collect best practices [here](https://developer.tibber.com/docs/guides/calling-api)

Let us know if in need of any assistance!

Br,
Toni
Tibber

**Comment by bisand** [comment]
> Hi!
> 
> I would like to thank you for contributing to the community of Tibber users! We've added you to the list of people we respect! https://developer.tibber.com/respect
> 
> In order to improve the API resilience we are making a breaking change for websocket communication. Please see details at [developer site](https://developer.tibber.com/). Would you be able to adjust the implementation accordingly?
> 
> Also, note that recommended format for setting user agent header would be to include both the platform version and driver version for example like this: MyHomeAutomationDevice/1.2.3 bisand/4.1.0'
> 
> We're trying to collect best practices [here](https://developer.tibber.com/docs/guides/calling-api)
> 
> Let us know if in need of any assistance!
> 
> Br, Toni Tibber

Hi, and thanks for the heads up.
I will go through the documentation and see if I am able to make the changes before the deadline in December. I will report back here on the progress.

Thanks!

**Comment by bisand** [comment]
@toini do you have a test endpoint that has already implemented the breaking changes? It would be nice to test the changes before publishing a new version.

**Comment by toini** [comment]
@bisand production does already support the breaking changes. You can try that for example at https://developer.tibber.com/explorer

**Comment by toini** [comment]
Hi @bisand,
I'm looking through the logs and I'm seeing a lot of reconnects for user agent bisand/tibber-api/5.0.0-beta.6. 101099 of them during the past 4 days. And, for example, during the past 24 hours one user reconnected 12 000 times.

What kind of reconnection logic do you have in place? Are you reconnecting if there is no data for x seconds, for example?

**Comment by bisand** [comment]
> Hi @bisand, I'm looking through the logs and I'm seeing a lot of reconnects for user agent bisand/tibber-api/5.0.0-beta.6. 101099 of them during the past 4 days. And, for example, during the past 24 hours one user reconnected 12 000 times.
> 
> What kind of reconnection logic do you have in place? Are you reconnecting if there is no data for x seconds, for example?

Hi @toini 
I see that I have a default reconnect timeout if no data is received for 30 seconds. This can also be changed by the user.
After reading a bit more on your documentation, I see that I will have to improve the reconnect logic. I will do some work the next few days to try to improve the logic.

**Comment by toini** [comment]
Thanks a lot @bisand! Exponential back off combined with checking whether a real time enabled device still exists would improve things a lot. Sounds like one user reconnecting 12 000 times a day has either tweaked reconnect interval a more frequent (once per 30 seconds would yield 2880 per day) or there could be something else going wrong triggering an immediate reconnect?

**Comment by bisand** [comment]
Hi @toini 
A new version of tibber-api is released which should address the connection issues. I have implemented exponential backoff with jitter and a check if real time subscription is enabled. Hopefully all consumers of the API will upgrade as soon as possible.
I will also deprecate all older versions on NPM for better communication.
If the problem remains, you can try to block problematic user agent versions. The user agent is automatically generated with correct version number during build, so it could make it easier for you to filter out potential bad versions in the future.
Please let me know if you see any other potential improvements

**Comment by toini** [comment]
Nice work! Is the newest version bisand/tibber-api/5.1.6? Ones with many reconnects seem to be running bisand/tibber-api/5.0.0-beta.6.

**Comment by bisand** [comment]
Yes, the newest version is bisand/tibber-api/5.1.6. All previous versions are deprecated in the NPM registry.

**Comment by bisand** [comment]
Closing.
