### ISSUE TITLE
Outdated documentation and inability to connect to Tibber Pulse

### ISSUE THREAD

**Issue by runbert** [bisand/tibber-api#29]
Hi there,

I've been trying to connect to Tibber Pulse using the Tibber API, but I'm having trouble with the examples provided in the documentation. The information provided in the documentation at the bottom seems to use old logic, and I'm not able to connect to Tibber Pulse using the new method stated in the beginning (old worked fine before the 5.0 update)

I followed the steps in the documentation, but I don't get any data. It would be great to have a fully working example there. It's a bit unclear if a feedUrl still should be provided in the config, and if that's the case should we use 'wss://websocket-api.tibber.com/v1-beta/gql/subscriptions' as Tibber states on their website or the one that's in the readme 'wss://api.tibber.com/v1-beta/gql/subscriptions'? This is the code I'm using at the moment:

```
const TibberFeed = require("tibber-api").TibberFeed;
const TibberQuery = require("tibber-api").TibberQuery;
var IConfig = require("tibber-api").IConfig;

  IConfig = {
        // Endpoint configuration.
        apiEndpoint: {
            apiKey: 'API-KEY',
            feedUrl: 'wss://websocket-api.tibber.com/v1-beta/gql/subscriptions',
            requestTimeout: 5000,
        },
        // Query configuration.
        homeId: '12341234-1234-451b-1234-f556f1233e8e',
        timestamp: true,
        power: true,
    };

    var query = new TibberQuery(pulseConfig, 30000);

    const tibberFeed = new TibberFeed(query);

    // Subscribe to "data" event.
    tibberFeed.on('data', data => {
        console.log(data)
    });

    // Subscribe to "connected" event.
    tibberFeed.on('connected', message => {
        console.log('Successfully connected to Tibber API!')
    });

    // Subscribe to "disconnected" event.
    tibberFeed.on('disconnected', message => {
        console.log('Disconnected from Tibber API. ' + message)
    });

    // Connect to Tibber data feed.
    tibberFeed.connect();

```
Can you spot any obvious mistake?

Thanks!

**Comment by bisand** [comment]
Hi,

Sorry for the outdated documentation. I will update the correct information as soon as possible. Meanwhile, the correct configuration should only contain a **queryUrl**, which at the moment is: [https://api.tibber.com/v1-beta/gql](https://api.tibber.com/v1-beta/gql). The feedUrl is deprecated and will automatically be retrieved by the api component.

**Comment by runbert** [comment]
Hi again,

Awesome, thanks alot for your help!

/Johan
