### ISSUE TITLE
Possible to add a Hourly consumption counter?

### ISSUE THREAD

**Issue by Sungtroll** [bisand/tibber-api#3]
Would have been nice to add Hour consumtion function like accumulatedConsumtionHour with counter that resets to zero every time the LastMeterConsumption value changes (at Txx:00:10). The Tibber AccumulatedConsumtion counter is reset at midnight.

**Comment by Sungtroll** [comment]
Tibber planning to add hourly consumption to the stream this weekend 13-14 mars 2021. Please be prepared to update tibberfeed with the new hourly consumplion counter that is reset every hour.

**Comment by bisand** [comment]
Ok. Do you have access to any links describing this change? I can't find any info about it in the Tibber API documentation

**Comment by Sungtroll** [comment]
The desicion to add the hourly consumtion counter was done today. The tibber backend developer starting to work on this tomorrow.

**Comment by bisand** [comment]
Thanks! I really appreciate your help!

**Comment by Sungtroll** [comment]
accumulatedConsumptionLastHour is up and running already.
{
  "liveMeasurement": {
    "timestamp": "2021-03-14T01:43:37.5+01:00",
    "power": 2612,
    "accumulatedConsumption": 5.516987,
    "accumulatedConsumptionLastHour": 2.046987
  }
}

Duplicates problem from tibber backend is also solved from now, last duplicate was 2021-03-14T00:00:27.5+01:00

Thank you bisand for making tibber-api feed for Node-Red, i really appreciate it :-)
