### ISSUE TITLE
Can not get example of Tibber Feed data to work properly

### ISSUE THREAD

**Issue by runbert** [bisand/tibber-api#30]
Hi!

I can not get the feed data from Tibber Pulse to work properly. I've tried creating a basic node-js app using the code below, but the console never logs any data from the tibber feed and the app ends instantly. 

```
const TibberFeed = require("tibber-api").TibberFeed;
const TibberQuery = require("tibber-api").TibberQuery;
var IConfig = require("tibber-api").IConfig;
var tibberQuery;
async function connectTibber() {
    // Config object needed when instantiating TibberQuery
    IConfig = {
        apiEndpoint: {
            apiKey: 'aX3eN6HXLfGasdExcEc983287aDSA', // Tibber token
            queryUrl: 'https://api.tibber.com/v1-beta/gql',
            requestTimeout: 5000,
        },
        homeId: '3dd82c34-4df4-412b-9fa2-f278387e90',
        timestamp: true,
        power: true,
    };
    // Instance of TibberQuery
    tibberQuery = new TibberQuery(IConfig);
    const tibberFeed = new TibberFeed(tibberQuery, 5000);
    // Subscribe to "data" event.
    tibberFeed.on('data', (data) => {
        console.log(data);
    });
    // Connect to Tibber data feed
    tibberFeed.connect();
}
connectTibber();
```

TibberQuery do though work by using `const queryHomes = '{ viewer { homes { currentSubscription { priceInfo { current { total energy tax startsAt } today { total energy tax startsAt } tomorrow { total energy tax startsAt } } } } } }'; 
const data = await tibberQuery.query(queryHomes);`

I've also tried using your provided code example but then the compiler complains about this:
`const config: IConfig = {
      ^^^^^^
SyntaxError: Missing initializer in const declaration`

Any ideas of what might be wrong? (I'm using the latest version of npm and tibber-api)
Thanks!

**Comment by bisand** [comment]
Hi,

The examples inside the repo is written in TypeScript and I assume you are trying to run them using Javascript. It's just a few steps required to convert them to pure javascript. First you need to remove the type declarations in all statements.
In your example you have removed the const declaration in the config variable, making the code execution fail.

Here's the problem:
```javascript
IConfig = { // MIssing the const/let declaration, and IConfig is already declared as a type above.
...
tibberQuery = new TibberQuery(IConfig); // Referencing IConfig type instead of a constant/variable.

```

The example below should work:
```javascript
const TibberFeed = require("tibber-api").TibberFeed;
const TibberQuery = require("tibber-api").TibberQuery;
var IConfig = require("tibber-api").IConfig;
var tibberQuery;
async function connectTibber() {
    // Config object needed when instantiating TibberQuery
    const config = { // Replaced the IConfig type with a constant.
        apiEndpoint: {
            apiKey: 'aX3eN6HXLfGasdExcEc983287aDSA', // Tibber token
            queryUrl: 'https://api.tibber.com/v1-beta/gql',
            requestTimeout: 5000,
        },
        homeId: '3dd82c34-4df4-412b-9fa2-f278387e90',
        timestamp: true,
        power: true,
    };
    // Instance of TibberQuery
    tibberQuery = new TibberQuery(config); // Using the constant declared above.
    const tibberFeed = new TibberFeed(tibberQuery, 5000);
    // Subscribe to "data" event.
    tibberFeed.on('data', (data) => {
        console.log(data);
    });
    // Connect to Tibber data feed
    tibberFeed.connect();
}
connectTibber();
```

Hope this solves your problem :)

**Comment by runbert** [comment]
Hi again,
Thanks for your quick answer!
The funny thing is, I still somehow can't get it work. The application just finishes running instantly with no log or error message in the console.
I've tried it in different environments but still the same problem.
I've also double checked the API-key and home-id at developer.tibber.com, and by using their API explorer web tool I manage to get a working connection to the pulse.
I've created a new public repo with the exact code that I'm running here: https://github.com/runbert/tibber-api-js-example

It would be really really nice if you could clone that one and see if you get a working connection to a pulse.

Thanks alot!!

/Johan

**Comment by runbert** [comment]
Making a little bump here…

Still havent solved it. Any ideas or should the issue be closed?

**Comment by frankoprifti** [comment]
I am having the same issue

**Comment by pieterbrandsen** [comment]
I found the issue,

@bisand @runbert @frankoprifti 

Its that active is missing in the config, this way it never allows it to connect, check out the connect function, in the example active would never be set so it never connects. By setting active to true before connecting you do get the data you want.

**Comment by bisand** [comment]
Closing this. Thanks for finding the solution @pieterbrandsen
