### ISSUE TITLE
Tibber is still reporting wrong cost in consumption data

### ISSUE THREAD

**Issue by hombach** [bisand/tibber-api#33]
![image](https://github.com/bisand/tibber-api/assets/63002482/29915aba-e3d9-4146-b6ae-e02825fc5585)

at least the hourly and monthly cost values aren't representing the cost alias total cost as it looks like in docmunetation.... so please add the deprecated query for totalCost .... at least as an option
(FYI: verified in Tibber Developer.... the data is still provided and correct)

**Comment by bisand** [comment]
Fixed in [v5.2.0](https://github.com/bisand/tibber-api/releases/tag/v5.2.0)
