### ISSUE TITLE
User Agent blocked 5.1.9

### ISSUE THREAD

**Issue by T1Fox** [bisand/tibber-api#39]
On query module i got this response sice today:

"{"responseMessage":"User agent bisand/tibber-api/5.1.9 is blocked. Please downgrade to the previous version or upgrade to a later version that works properly","httpCode":400,"statusCode":400,"statusMessage":"Bad Request"}"

**Comment by bisand** [comment]
A new version with a new user agent has been deployed. Please try to upgrade to see if it helps.
Alternative: Add a string to the userAgent property in apiEndpoint config

**Comment by hombach** [comment]
5.1.11 works with test system 1 .... trying next one

**Comment by hombach** [comment]
my main system also works with tibber-api 5.1.11    that's fine  .... now I have to get this to >>2000 users LOL

**Comment by bisand** [comment]
I would recommend adding a unique string to the [userAgent](https://github.com/bisand/tibber-api/blob/8e167198d095f3e85894566b1577b130b0d3f753/src/models/IEndpoint.ts#L4) in the apiEndpoint under config when creating TibberQuery. That will be included as a prefix to the default userAgent string.

That should make your user agent different from any other users.

Tibber can from time to time block userAgents that generate exessive traffic, og for any other reasons.

**Comment by hombach** [comment]
Hi André - doesn*t look like that there*s a significant difference upon use of the unique string

**Comment by hombach** [comment]
Got several positive response ..... looks like you might close this issue

**Comment by jstaro** [comment]
@hombach If you have 2000 users, I'd advise you to use your own `ioBroker`-based user-agent or set it as a prefix to this one, so we can distinguish your (hopefully) well-behaved integration from other users of this library. It's win-win because that makes it easier for us to know who to contact, if need be, to make things run smoothly for

a. all users of the API, including, of course, yours
b. Tibber

in that order.

Best,
Jon @ Tibber

**Comment by hombach** [comment]
@jstaro Hi Jon I agree - let's please switch communication to TibberLink@homba.ch.... 
I'm using bisand's lib - as you wrote in a parallel issue "we have not yet seen any bad behavior by any clients reporting the 5.1.11 user-agent" - so looks like my integration is also behaving well ;)
