### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by Sungtroll** [bisand/tibber-api#4]
Sometimes duplicates are sent so i have to do a duplicate check, Sometimes messages got lost. I am using only timestamp, accumulatedconsumption, power and powerfactor. If counting energy consumption out of power/1440000 from every received message the energy consumption will be wrong.

**Comment by bisand** [comment]
Hi @Sungtroll, I haven't had the chance to work with this for a while now. Does the problem still remain? And could you please provide some more information to ease the research/debugging?

To be clear, this could be a Tibber-problem since the data is not manipulated on its way from Tibber. It would be nice if you could provide sample data from Tibber's own API explorer and compare it with the result from this tibber-api component.

If you find a bug yourself, please feel free to submit a pull request.

**Comment by Sungtroll** [comment]
I use the following code to log the duplicate repeated messages.
timestamp=flow.get("timestamp") ||0;
var duplicates=flow.get("duplicates")||0;
msg.payload.duplicates=duplicates; // To display count of duplicates in UI text.
if (timestamp==msg.payload.timestamp) {flow.set("duplicates", duplicates+1); msg.payload=duplicates+1 +" "+msg.payload.timestamp; return [null,msg]} //Output goes to output 2 to add to duplicate log file
flow.set("timestamp",msg.payload.timestamp);
return msg

It seems to happens every other minute and always at 27.5 seconds. Somtimes 4 minutes between duplicate messages.

Tibberfeed messages logged stright to text file saved:
{"timestamp":"2021-03-11T14:04:22.5+01:00","power":954}
{"timestamp":"2021-03-11T14:04:25+01:00","power":955}
{"timestamp":"2021-03-11T14:04:27.5+01:00","power":956} Message 
{"timestamp":"2021-03-11T14:04:27.5+01:00","power":956} THIS MESSAEGE IS A DUPLICATE MESSAGE OF THE ABOVE MESSAGE THAT IS REPEATED
{"timestamp":"2021-03-11T14:04:30+01:00","power":959}
{"timestamp":"2021-03-11T14:04:32.5+01:00","power":949}

From the duplicates count logged text file saved shows 66100 messages was repeated from start of logging the 22.12.2020.
duplicate message count# msg.payload.timestamp
66100 2021-03-11T14:04:27.5+01:00 
66101 2021-03-11T14:08:27.5+01:00 //This time 4 minutes
66102 2021-03-11T14:10:27.5+01:00 //2 minutes
66103 2021-03-11T14:12:27.5+01:00 //2 minutes
66104 2021-03-11T14:14:27.5+01:00 //2 minutes
66105 2021-03-11T14:16:27.5+01:00 //2 minutes
66106 2021-03-11T14:18:27.5+01:00 //2 minutes
66107 2021-03-11T14:20:27.5+01:00 //2 minutes
66108 2021-03-11T14:22:27.5+01:00 //2 minutes
66109 2021-03-11T14:24:27.5+01:00 //2 minutes

**Comment by bisand** [comment]
Thanks for spending time to investigate! 👍

**Comment by Sungtroll** [comment]
Duplicates problem at tibber backend is solved from now, last duplicate was 2021-03-14T00:00:27.5+01:00

**Comment by Sungtroll** [comment]
I modified to include accumulatedConsumtionLastHour and it works fine except if ticking the check boxes on or off there is several duplicates until i restart node-red. Some messages comes with the new check boxed values, but repeated message without. Seems like two prosesses running at same time querying tibber endpoint but with different query one old and one new. See example below, note the timestamp is equal but message is with or without accumulatedConsumption that i ticked in the check box.

{"timestamp":"2021-03-17T18:54:52.5+01:00","power":565,"lastMeterConsumption":11908.22,"accumulatedConsumptionLastHour":0.537368,"minPower":474,"averagePower":846.3,"maxPower":5504,"powerFactor":null,"voltagePhase1":null,"voltagePhase2":null,"voltagePhase3":null,"currentL1":null,"currentL2":null,"currentL3":null}
{"timestamp":"2021-03-17T18:54:55+01:00","power":566,"lastMeterConsumption":11908.22,"accumulatedConsumption":16.007761,"accumulatedConsumptionLastHour":0.537761,"minPower":474,"averagePower":846.3,"maxPower":5504,"powerFactor":null,"voltagePhase1":null,"voltagePhase2":null,"voltagePhase3":null,"currentL1":null,"currentL2":null,"currentL3":null}
{"timestamp":"2021-03-17T18:54:55+01:00","power":566,"lastMeterConsumption":11908.22,"accumulatedConsumptionLastHour":0.537761,"minPower":474,"averagePower":846.3,"maxPower":5504,"powerFactor":null,"voltagePhase1":null,"voltagePhase2":null,"voltagePhase3":null,"currentL1":null,"currentL2":null,"currentL3":null}

![image](https://user-images.githubusercontent.com/37970110/111512041-9ceee480-874f-11eb-87a4-bbd6af89a358.png)

**Comment by Sungtroll** [comment]
closed and opening as new issue in node-red-contrib-tibber-api
