### ISSUE TITLE
Error: Cannot find module 'cross-fetch'

### ISSUE THREAD

**Issue by runbert** [bisand/tibber-api#8]
Just a heads up:

When running tibber-api in npm RunKit (https://npm.runkit.com/tibber-api), it throws the following error:

```
Error: Cannot find module 'cross-fetch'

in tibber-api/lib/src/nodes/TibberQuery.js — line 5
```

Has it always been like that and should we just ignore it?

**Comment by bisand** [comment]
Hi, thanks for notifying me. I've corrected it and published a new version. 3.0.1 should work without throwing this error.

**Comment by runbert** [comment]
Great! RunKit now seems to run just fine without any errors. Thanks!
