### ISSUE TITLE
User agent header value contains extra chars

### ISSUE THREAD

**Issue by toini** [bisand/tibber-api#91]
Hi! We at Tibber noticed that the user agent being reported in version 5.1.11 has many different forms. 

Here's a few:
```
G4vApLpB2rnGgP1function now() { [native code] } bisand/tibber-api/5.1.11
G6X9bMYdw6EGfa3function now() { [native code] } bisand/tibber-api/5.1.11
G7Ip2Rg0mvR0wHifunction now() { [native code] } bisand/tibber-api/5.1.11
G7Mu4qa90OdYTD9function now() { [native code] } bisand/tibber-api/5.1.11
```

Looks like it's being populated with something extra?

**Comment by bisand** [comment]
> Hi! We at Tibber noticed that the user agent being reported in version 5.1.11 has many different forms.
> 
> Here's a few:
> 
> ```
> G4vApLpB2rnGgP1function now() { [native code] } bisand/tibber-api/5.1.11
> G6X9bMYdw6EGfa3function now() { [native code] } bisand/tibber-api/5.1.11
> G7Ip2Rg0mvR0wHifunction now() { [native code] } bisand/tibber-api/5.1.11
> G7Mu4qa90OdYTD9function now() { [native code] } bisand/tibber-api/5.1.11
> ```
> 
> Looks like it's being populated with something extra?

That is probably because someone using the library is adding their own user agent string. See code here:
https://github.com/bisand/tibber-api/blob/8e167198d095f3e85894566b1577b130b0d3f753/src/nodes/TibberQueryBase.ts#L81
and here:
https://github.com/bisand/tibber-api/blob/8e167198d095f3e85894566b1577b130b0d3f753/src/nodes/TibberFeed.ts#L381

The feature was introduced so that users of the library could identify themselves without running the risk of being blocked by other users.

Let me know if you think that should be changed.

**Comment by toini** [comment]
Hi @bisand I think this clearly unintentional. Printing `"now() { [native code] }"`  is Javascript trying to print something that was provided to it but turns out to be binary. It looks like it's probably something that includes a function pointer?

**Comment by toini** [comment]
Ah had to re-read to understand :) Looks like all users are passing something binary. Are you sure passing a string results in the concatenation of that string and yours?

**Comment by bisand** [comment]
Hi @toini, I am quite sure I am concatenating a string result.

The user agent is defined as a "nullable" string:
https://github.com/bisand/tibber-api/blob/f5a317d974676793a36b52eb657db5888296e798/src/models/IEndpoint.ts#L4
but I cannot guarantee that the user using this library is doing everything "by the book".
The version of the TibberApi library is defined in the line below:
https://github.com/bisand/tibber-api/blob/f5a317d974676793a36b52eb657db5888296e798/Version.ts#L1

I should probably do some verifications and only allow cartain characters. Either by throwing an exception or removing the unwanted ones.

What do you suggest is the best approach?

**Comment by toini** [comment]
Interesting. Majority of the users connecting seem to be passing this binary thingy. I wonder if there could be a common denominator among them? A copy paste from somewhere? Do you know a user (email, id or ip) who 100% sets a value with a string so i could check how that appears?

![image](https://github.com/user-attachments/assets/2494bba0-e5b7-491d-b3c1-895dd7c81972)

**Comment by bisand** [comment]
Indeed, very interesting!

I will take a closer look at it and also wrap some unit tests around it to verify the validity. It might take a few days, but I can check back again when I hade the time to do so :)

**Comment by bisand** [comment]
I have published new versions of both [bisand/tibber-api ](https://github.com/bisand/tibber-api/)and [bisand/node-red-contrib-tibber-api/](https://github.com/bisand/node-red-contrib-tibber-api/) that contains a strenghtened version of User-Agent handling. Once the library has been instantiated, the User-Agent can not be altered, so random user-agent strings should occurr less often. Then again, it also depends on how other library consumers are implementing it.

The User-Agent string is also validated to try to comply with the [current guidelines](https://tools.ietf.org/html/rfc7231#section-5.5.3) 

The implementation can be found here: https://github.com/bisand/tibber-api/blob/8a2a96488d3e1fa947ee0e5489e3156544e07397/src/tools/HeaderManager.ts#L26

To identify potential culprits, you can also take a look at libraries using tibber-api. Maybe the can shed some light on who's generating the user-agets in question: https://www.npmjs.com/package/tibber-api?activeTab=dependents
